# Site settings
title: University blog
email: singlett@uni.coventry.ac.uk
description: "A blog for University related posts"
baseurl: ""
url: "RDevBlog.com"

# Build settings
markdown: kramdown
permalink: pretty
